# 公共配置文件
spring:
  rabbitmq:
    host: 106.53.68.162
    port: 5672
    password: LiangHaoxuanAdmin
    username: Lhx20021030!
    virtual-host: /
  application:
    name: goodchoiceoj-backend
  # 默认 dev 环境
  #  profiles:
  #    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.53.68.162:3306/goodchoiceoj
    username: root
    password: Lhx20021030!
  # Redis 配置
  redis:
    database: 1
    host: 106.53.68.162
    port: 6379
    timeout: 50000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    password: Lhx20021030!
  servlet:
    multipart:
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

#代码沙箱配置
codesandbox:
  type: remote